const qnaList = [
  {
    q: '기본-1) 평균 수면시간이 어떻게 되시나요?',
    aType: 'select',
    info: '사람이 자는 동안에도 단백질 합성이 일어나고, 몸이 회복됩니다. 카제인과 같이 몸에 천천히 소화되는 단백질은 밤새 지속적인 근육 회복을 가능하게 해줍니다.',
    a: [
      { answer: '6시간 미만', type: 'noCasein' },
      { answer: '6시간 이상', type: null },
    ],
  },
  {
    q: '기본-2) 우유 포함 제품(유제품)을 섭취 시 속이 불편하다.',
    info: '대부분의 단백질 보충제는 우유에서 추출한 유청단백질을 주된 원재료로 사용하기 때문에 유당불내증 여부를 판단하여 추천합니다.(우유에 민감하시면 그렇다 라고 해주세요!)',
    aType: 'select',
    a: [
      { answer: '그렇다.', type: 'hateMilk' },
      { answer: '아니다.', type: null },
    ],
  },
  {
    q: '기본-3) 일반적인 단백질 보충제를 섭취했을 때, 여드름이 올라온다.',
    info: '유청단백질(단백질 보충제의 주된 원료)을 섭취했을 때, 체내 IGF-1 분비로 인하여 피지 분비 각질 세포 성장을 촉진시킬 수 있다.',
    aType: 'select',
    a: [
      { answer: '그렇다.', type: 'veg' },
      { answer: '아니다.', type: null },
    ],
  },
  {
    q: '기본-4) 섭취할 수 없는 성분이 있다면 골라주세요.',
    aType: 'multSelect',
    info: 'Coup에서는 식이 제한으로 섭취하지 못하는 성분이 들어간 제품을 제외하고 추천하도록 설계되어 있습니다.',
    a: [
      { answer: '글루텐', type: 'noGluten' },
      { answer: '동물성(비건)', type: 'veg' },
      { answer: '카페인', type: 'noCaffeine' },
      { answer: '딱히 없다.', type: null },
    ],
  },
  {
    q: '운동-1) 나의 운동 목표는?',
    aType: 'select',
    info: 'Coup이 권장하는 단백질 보충제는 운동 목표에 따라 다릅니다. 10g 당 함유된 단백질, 지방, 탄수화물을 척도로 하여 운동 목표에 맞는 제품을 추천해줍니다.',
    a: [
      { answer: '체중 감량', type: 'diet' },
      { answer: '근력 향상', type: 'strength' },
      { answer: '벌크업', type: 'bulk' },
    ],
  },
  {
    q: '운동-2) 주로 어느 시간에 운동하시나요?',
    aType: 'select',
    info: '개인의 운동 시간대 정보는 추천 제품의 카페인 포함 여부를 결정하는데 도움이 됩니다. 카페인은 운동 성능을 극대화하는 성분으로 알려져 있지만, 늦은 밤에 섭취 시 수면을 방해할 수 있습니다.',
    a: [
      { answer: '아침(4시~12시)', type: null },
      { answer: '오후(12시 ~ 18시)', type: null },
      { answer: '저녁(18시~0시)', type: 'noCaffeine' },
      { answer: '새벽(0시~4시)', type: 'noCaffeine' },
    ],
  },
];

const infoList = [
  // 컴뱃
  {
    name: '컴뱃 100% 웨이프로틴',
    img: 'https://cdn.shopify.com/s/files/1/1618/2767/products/SportSeries_Combat100Whey_5lb_Strawberry_view1_650x.jpg?v=1559580599',
    link: 'https://coupa.ng/bVlOZ0',
    protein_ten: 7.58,
    fat_ten: 0.45,
    carbo_ten: 0.91,
    cal_ten: 39.39,
    type: ['noCasein', 'noGluten', 'noCaffeine', 'diet', 'strength'],
  },
  {
    name: '컴뱃 아이솔레이트 프로틴 파우더',
    img: 'https://thumbnail8.coupangcdn.com/thumbnails/remote/492x492ex/image/vendor_inventory/images/2019/01/31/11/8/a5e07da4-72bd-46d5-abb1-26afe2f8463d.jpg',
    link: 'https://coupa.ng/bVlPAA',
    protein_ten: 8.89,
    fat_ten: 0,
    carbo_ten: 0,
    cal_ten: 37.04,
    type: ['wpi', 'noCasein', 'hateMilk', 'noGluten', 'noCaffeine', 'diet', 'strength'],
  },
  {
    name: '컴뱃 XL 매스 게이너',
    img: 'https://cdn.shopify.com/s/files/1/1618/2767/products/SportSeries_CombatXLMassGainer_6lb_Vanilla_view1_650x.jpg?v=1559162878',
    link: 'https://coupa.ng/bVlPSc',
    protein_ten: 1.51,
    fat_ten: 0.24,
    carbo_ten: 7.56,
    cal_ten: 38.55,
    type: ['noGluten', 'noCaffeine', 'bulk'],
  },
  // BSN
  {
    name: '신타-6 프로틴 파우더',
    img: 'https://www.gobsn.com/sites/g/files/mrktmf196/files/syntha-6_0.png',
    link: 'https://coupa.ng/bVlL6K',
    protein_ten: 4.68,
    fat_ten: 1.28,
    carbo_ten: 3.19,
    cal_ten: 42.55,
    type: ['noCaffeine', 'strength'],
  },
  {
    name: '신타-6 아이솔레이트 프로틴 파우더',
    img: 'https://www.gobsn.com/sites/g/files/mrktmf196/files/syntha6-isolate.png',
    link: 'https://coupa.ng/bVlNp4',
    protein_ten: 6.58,
    fat_ten: 0.39,
    carbo_ten: 1.84,
    cal_ten: 36.84,
    type: ['wpi', 'noCasein', 'hateMilk', 'noGluten', 'noCaffeine', 'strength'],
  },
  {
    name: '신타-6 엣지 프로틴 파우더',
    img: 'https://www.gobsn.com/sites/g/files/mrktmf196/files/syntha6edge.png',
    link: 'https://coupa.ng/bVlNRC',
    protein_ten: 6.23,
    fat_ten: 0.91,
    carbo_ten: 1.82,
    cal_ten: 38.96,
    type: ['noGluten', 'noCaffeine', 'strength'],
  },
  {
    name: '비에스엔 트루매스 울트라',
    img: 'https://www.gobsn.com/sites/g/files/mrktmf196/files/truemass.png',
    link: 'https://coupa.ng/bVlOgh',
    protein_ten: 2.79,
    fat_ten: 1.09,
    carbo_ten: 5.27,
    cal_ten: 42.42,
    type: ['noCaffeine', 'bulk'],
  },
  {
    name: '비에스엔 트루매스 1200',
    img: 'https://www.gobsn.com/sites/g/files/mrktmf196/files/truemass-1200.png',
    link: 'https://coupa.ng/bVlOtB',
    protein_ten: 1.61,
    fat_ten: 0.52,
    carbo_ten: 7.16,
    cal_ten: 39.68,
    type: ['noCaffeine', 'bulk'],
  },
  // 옵티멈 뉴트리션
  {
    name: '옵티멈뉴트리션 골드 스탠다드 웨이 프로틴',
    img: 'https://content.optimumnutrition.com/i/on/on-gold-standard-100-whey-protein_Image_01?layer0=$PDP-MOB$&img404=no-product-image&v=1&locale=en-gb,*',
    link: 'https://coupa.ng/bVmxWH',
    protein_ten: 7.89,
    fat_ten: 0.49,
    carbo_ten: 0.99,
    cal_ten: 39.47,
    type: ['noGluten', 'noCasein', 'noCaffeine', 'diet', 'strength'],
  },
  {
    name: '옵티멈뉴트리션 플래티넘 하이드로 웨이 프로틴 아이솔레이트',
    img: 'https://content.optimumnutrition.com/i/on/on-hydrowhey-optimum-nutrition_Image_01?layer0=$PDP-MOB$&img404=no-product-image&v=1&locale=en-gb,*',
    link: 'https://coupa.ng/bVrIwC',
    protein_ten: 7.69,
    fat_ten: 0.26,
    carbo_ten: 0.77,
    cal_ten: 35.9,
    type: ['wpi', 'hateMilk', 'noCasein', 'noGluten', 'noCaffeine', 'diet', 'strength'],
  },
  {
    name: '옵티멈뉴트리션 골드 스탠다드 100% 카제인',
    img: 'https://content.optimumnutrition.com/i/on/on-100-casein-time-release-proteine_Image_01?layer0=$PDP-MOB$&img404=no-product-image&v=1&locale=en-gb,*',
    link: 'https://coupa.ng/bVrPmO',
    protein_ten: 7.06,
    fat_ten: 0.29,
    carbo_ten: 0.88,
    cal_ten: 35.29,
    type: ['noGluten', 'noCaffeine', 'diet', 'strength'],
  },
  {
    name: '옵티멈뉴트리션 식물 프로틴',
    img: 'https://content.optimumnutrition.com/i/on/on-C100027_Image_01?layer0=$PDP_002$&img404=no-product-image&v=1&locale=en-gb,*',
    link: 'https://coupa.ng/bVrTsw',
    protein_ten: 6.67,
    fat_ten: 0.69,
    carbo_ten: 1.67,
    cal_ten: 38.89,
    type: ['veg', 'hateMilk', 'noGluten', 'noCasein', 'noCaffeine', 'strength'],
  },
  {
    name: '옵티멈뉴트리션 시리어스 매스',
    img: 'https://content.optimumnutrition.com/i/on/on-serious-mass_Image_01?layer0=$PDP-MOB$&img404=no-product-image&v=1&locale=en-us,en-gb,*',
    link: 'https://coupa.ng/bXdbvk',
    protein_ten: 1.5,
    fat_ten: 0.13,
    carbo_ten: 7.57,
    cal_ten: 38.32,
    type: ['noCaffeine', 'bulk'],
  },
  // 칼로바이
  {
    name: '칼로바이 퍼펙트 파워쉐이크',
    img: 'https://thumbnail9.coupangcdn.com/thumbnails/remote/492x492ex/image/retail/images/42322644562739-5c7dd7b9-a780-4bb9-a1fe-c1432d6ee273.jpg',
    link: 'https://coupa.ng/bVl3Vj',
    protein_ten: 7.05,
    fat_ten: 0.3,
    carbo_ten: 2.27,
    cal_ten: 37.5,
    type: ['noCaffeine', 'noCasein', 'strength'],
  },
  {
    name: '칼로바이 퍼펙트 파워쉐이크 포대유청 WPC',
    img: 'https://thumbnail10.coupangcdn.com/thumbnails/remote/492x492ex/image/retail/images/13056725373943-61497a5e-c78b-43da-b314-c81807f63800.png',
    link: 'https://coupa.ng/bVl7Ex',
    protein_ten: 7.43,
    fat_ten: 0.33,
    carbo_ten: 1.37,
    cal_ten: 38.33,
    type: ['noCaffeine', 'noCasein', 'strength'],
  },
  {
    name: '칼로바이 다밀 뉴트리션 단백질쉐이크 오곡맛',
    img: 'https://thumbnail7.coupangcdn.com/thumbnails/remote/492x492ex/image/retail/images/531871443445755-cd76a107-8ad2-454e-91c1-6c74c5aa2904.jpg',
    link: 'https://coupa.ng/bVmbtj',
    protein_ten: 2,
    fat_ten: 0.73,
    carbo_ten: 4,
    cal_ten: 30.5,
    type: ['noCasein', 'noCaffeine', 'strength', 'bulk', 'diet'],
  },
  {
    name: '칼로바이 퍼펙트 파워쉐이크 아이솔레이트',
    img: 'https://thumbnail7.coupangcdn.com/thumbnails/remote/230x230ex/image/vendor_inventory/4c10/6ddfe62da592413f60c8fd9fba7f2e78ca8cb74459fc063740dee2cadcda.jpg',
    link: 'https://coupa.ng/bXcz9E',
    protein_ten: 6.55,
    fat_ten: 0.48,
    carbo_ten: 2.62,
    cal_ten: 38.57,
    type: ['wpi', 'hateMilk', 'noGluten', 'noCasein', 'noCaffeine', 'strength'],
  },
  // 마이프로틴
  {
    name: '임팩트 웨이 프로틴',
    img: 'https://s1.thcdn.com/productimg/1600/1600/10530943-1504726884876366.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/impact-whey-protein/10530943.html?autocomplete=productsuggestion',
    protein_ten: 8.2,
    fat_ten: 0.75,
    carbo_ten: 0.4,
    cal_ten: 41.2,
    type: ['noGluten', 'noCaffeine', 'diet', 'noCasein', 'strength'],
  },
  {
    name: '임팩트 웨이 아이솔레이트',
    img: 'https://s3.thcdn.com/productimg/1600/1600/10530911-2014620651215604.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/impact-whey-isolate/10530911.html?autocomplete=productsuggestion',
    protein_ten: 9,
    fat_ten: 0.03,
    carbo_ten: 0.25,
    cal_ten: 37.3,
    type: ['wpi', 'hateMilk', 'noGluten', 'noCaffeine', 'noCasein', 'diet', 'strength'],
  },
  {
    name: '웨이트 게이너 블렌드',
    img: 'https://s1.thcdn.com/productimg/1600/1600/10529988-1004620647157420.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/weight-gainer-blend/10529988.html',
    protein_ten: 3.14,
    fat_ten: 0.62,
    carbo_ten: 5,
    cal_ten: 38.8,
    type: ['noCaffeine', 'noCasein', 'bulk'],
  },
  {
    name: '완두콩 프로틴 아이솔레이트',
    img: 'https://s3.thcdn.com/productimg/1600/1600/10530136-1624839379406715.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/pea-protein-isolate/10530136.html',
    protein_ten: 7.5,
    fat_ten: 0.5,
    carbo_ten: 0.3,
    cal_ten: 35.7,
    type: ['veg', 'hateMilk', 'noGluten', 'noCasein', 'noCaffeine', 'diet', 'strength'],
  },
  {
    name: '클리어 웨이 아이솔레이트',
    img: 'https://s3.thcdn.com/productimg/960/960/12081396-1994792209042321.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/clear-whey-isolate/12081395.html?autocomplete=productsuggestion',
    protein_ten: 8,
    fat_ten: 0.05,
    carbo_ten: 0.27,
    cal_ten: 33.4,
    type: ['noGluten', 'noCasein', 'noCaffeine', 'diet', 'strength'],
  },
  {
    name: '100% 인스턴트 오트',
    img: 'https://s3.thcdn.com/productimg/960/960/10529296-1524620644465835.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/100-instant-oats/10529296.html?autocomplete=productsuggestion',
    protein_ten: 1.1,
    fat_ten: 0.77,
    carbo_ten: 6.2,
    cal_ten: 38.4,
    type: ['veg', 'hateMilk', 'noCasein', 'noCaffeine', 'bulk'],
  },
  {
    name: '현미 프로틴',
    img: 'https://s2.thcdn.com/productimg/960/960/10530779-4264839381960657.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/brown-rice-protein/10530779.html',
    protein_ten: 7.8,
    fat_ten: 0.21,
    carbo_ten: 0.38,
    cal_ten: 42.3,
    type: ['veg', 'hateMilk', 'noCaffeine', 'noCasein', 'diet', 'strength'],
  },
  {
    name: '100% 글루텐 프리 오트롤',
    img: 'https://s4.thcdn.com/productimg/960/960/11247305-1124690584137763.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/100-gluten-free-rolled-oats/11247305.html',
    protein_ten: 1.2,
    fat_ten: 0.62,
    carbo_ten: 6.1,
    cal_ten: 36.6,
    type: ['veg', 'hateMilk', 'noCasein', 'noCaffeine', 'bulk'],
  },
  {
    name: '임팩트 다이어트 웨이',
    img: 'https://s4.thcdn.com/productimg/960/960/10530657-1834620650702430.jpg',
    link: 'https://www.myprotein.co.kr/sports-nutrition/impact-diet-whey/10530657.html?autocomplete=productsuggestion',
    protein_ten: 6.5,
    fat_ten: 0.64,
    carbo_ten: 0.94,
    cal_ten: 37.2,
    type: ['noCasein', 'noCaffeine', 'diet', 'strength'],
  },
];
